version: '{build}'
skip_tags: true
image: Visual Studio 2022
install:
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Seq.Input.RabbitMQ.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: HDcRadKRDne9Gd1vEQwZknRQz63ZbZMJh6e4sFmiXCpjkxC5WCoQ0ZecWBHtVulX
  skip_symbols: true
  on:
    branch: /^(main|dev)$/
- provider: GitHub
  auth_token:
    secure: hX+cZmW+9BCXy7vyH8myWsYdtQHyzzil9K5yvjJv7dK9XmyrGYYDj/DPzMqsXSjo
  artifact: /Seq.Input.RabbitMQ.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: main
