version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
install:
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Seq.Input.RabbitMQ.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: XqbN2YjJ/L0u8RG4uyFzPm6Qf5Bhy+80n9+WyNs9p19ZqdRCurea87gMxbXR93Wi
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: hX+cZmW+9BCXy7vyH8myWsYdtQHyzzil9K5yvjJv7dK9XmyrGYYDj/DPzMqsXSjo
  artifact: /Seq.Input.RabbitMQ.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
